application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /my-images
  static_dir: my-images

#added this to connect to inputpage
- url: /html
  static_dir: html

#new handlers should go ABOVE the catch all url (.*)
- url: .*
  script: main.app
  login: required


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
